# Numpy

- Let's discuss a library called Numpy.
- Python arrays (or lists) in general are a little slow; Python lists in general are a little slow. There are couple of reasons for that:
    - Given the fact that a Python list can store anything such as integers, floats, strings, and other lists, it's not stored in a very compact way and takes a lot of space.
    - Python arrays (or lists) are actually a little slow because Python in general is a little slower than languages like C++, C.
- So what we are going to use is Numpy.
    - Numpy arrays will have elements of same type and hence they are stored compactly.
    - And the Numpy code itself is mostly written in C, so actually it is very fast as well.
    - So Numpy arrays are much faster than the normal lists that we use and hence more widely used.

In [2]:
import numpy as np

In [3]:
l1 = [12, 23, 37]
np.array(l1)

array([12, 23, 37])

In [4]:
l2 = [56, 67, "99"]
np.array(l2)
# If one of the elements in the list is a string, it will convert all the elements of the list as strings.

array(['56', '67', '99'], dtype='<U21')

In [5]:
# How to create numpy arrays
l = [1, 2, 3]
a = np.array(l)


b = np.zeros(10)

c = np.ones(10)
c

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
c2 = np.ones(10, int)
c2

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [7]:
c2[0] = "0"
# converts the string "0" to integer 0
c2

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [8]:
c.dtype

dtype('float64')

In [9]:
# create 2D array
d = np.zeros((2,3))
d

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
# create multidimensional arrays
# example of a 3D array
e = np.zeros((2, 3, 4))
e

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [11]:
# Accessing data
a1 = [3467, 2323, 12231, 4545, 77676]
a2 = np.array(a1)
print(a2[0])
print(a2[2])

a3 = np.zeros((2, 3), int)
print(a3)
print(a3[0])
print(a3[1][1])

3467
12231
[[0 0 0]
 [0 0 0]]
[0 0 0]
0


In [12]:
# slicing
print(a2[2:4])
print(a2[:3])

[12231  4545]
[ 3467  2323 12231]


In [13]:
# shape gives the size
print(a2.shape)
print(a3.shape)
print(e.shape)

(5,)
(2, 3)
(2, 3, 4)


In [14]:
# accessing rows and columns from a 2D numpy array
p = np.array([[1, 2, 3], [4, 5, 6]])
# accessing 0th row
p[0]

array([1, 2, 3])

In [15]:
# accessing 0th column
p[:, 0]

array([1, 4])

In [16]:
# accessing parts of rows and columns from a 2D numpy array
q = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
q

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [17]:
# accessing first row elements from 2nd element (or column) to last element (or column)
q[0, 1:]

array([2, 3])

In [18]:
# accessing the complete 2nd column elements
q[:,1]

array([ 2,  5,  8, 11])

In [19]:
# accessing subarrays from a 2D array
q[1:3, 1:]

array([[5, 6],
       [8, 9]])

In [20]:
# accessing subarrays from a 2D array
q[2:, :2]

array([[ 7,  8],
       [10, 11]])

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# Numpy Operations
a21 = np.array([1, 2, 3])
a21 + 2

array([3, 4, 5])

In [23]:
a22 = np.array([4, 5, 6])
a21 + a22

array([5, 7, 9])

In [24]:
a21 * 2

array([2, 4, 6])

In [25]:
a21 * a22

array([ 4, 10, 18])

In [26]:
a21 ** 3

array([ 1,  8, 27])

In [27]:
a21 ** a22

array([  1,  32, 729])

In [28]:
a21 / 2

array([0.5, 1. , 1.5])

In [29]:
a21 / a22

array([0.25, 0.4 , 0.5 ])

In [30]:
a21 // 2

array([0, 1, 1])

In [31]:
a21 // a22

array([0, 0, 0])

In [32]:
a21.mean()

2.0

In [33]:
a21.sum()

6

In [34]:
# finding squared distance in n dimensional space
import math

a23 = np.array([1, 2, 3])
a24 = np.array([5, 6, 7])
d = ((a23 - a24) ** 2).sum()
math.sqrt(d)

6.928203230275509

Generally things become very easy by using numpy arrays. For example, given below is the formula for standard deviation which can be calculated using numpy arrays.

![](images/numpy1.png)

In [35]:
x = np.array([12.23, 34.56, 75.14, 98.23])
sd = math.sqrt(((x -  x.mean()) ** 2).sum() / x.shape[0])
sd

33.621096799479936

In [36]:
np.sum([[0, 1], [0, 5]], axis=1)

array([1, 5])